bbsnote/urls.py
from django.urls import path
from . import views

app_name = 'bbsnote'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:board_id>/', views.detail, name='detail'),
    path('comment/create/<int:board_id>/', views.comment_create, name='comment_create'),
    path('board/create', views.board_create, name='board_create'),
    path('board/modify/<int:board_id>/', views.board_modify, name='board_modify'),
    path('board/delete/<int:board_id>', views.board_delete, name='board_delete'),
    path('comment/modify/<int:comment_id>/', views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
]

common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'common'

urlpatterns =[
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from bbsnote import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bbsnote/', include('bbsnote.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),
    path('insta/', include('insta.urls'))
]

insta/urls.py
from django.urls import path
from . import views

app_name = 'insta'

urlpatterns = [
    path('', views.index, name='index'),
    path('wordcloud/', views.wordcloud, name='wordcloud'),
    path('map/', views.map, name='map'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" 
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" 
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" 
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" 
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" 
        integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" 
        crossorigin="anonymous"></script>
</head>
<body>
    {% include "navbar.html" %}
    
    {% block content %}
    {% endblock %}
    {% block script %}
    {% endblock %}
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/map.html
<!DOCTYPE html>
<html>
<head>
    
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    
        <script>
            L_NO_TOUCH = false;
            L_DISABLE_3D = false;
        </script>
    
    <style>html, body {width: 100%;height: 100%;margin: 0;padding: 0;}</style>
    <style>#map {position:absolute;top:0;bottom:0;right:0;left:0;}</style>
    <script src="https://cdn.jsdelivr.net/npm/leaflet@1.9.3/dist/leaflet.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.9.3/dist/leaflet.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.0/css/all.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/python-visualization/folium/folium/templates/leaflet.awesome.rotate.min.css"/>
    
            <meta name="viewport" content="width=device-width,
                initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
            <style>
                #map_4793c1a92a72505a3700db591b3bc783 {
                    position: relative;
                    width: 100.0%;
                    height: 100.0%;
                    left: 0.0%;
                    top: 0.0%;
                }
                .leaflet-container { font-size: 1rem; }
            </style>
        
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.1.0/leaflet.markercluster.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.1.0/MarkerCluster.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.1.0/MarkerCluster.Default.css"/>
</head>
<body>
    
    
            <div class="folium-map" id="map_4793c1a92a72505a3700db591b3bc783" ></div>
        
</body>
<script>
    
    
            var map_4793c1a92a72505a3700db591b3bc783 = L.map(
                "map_4793c1a92a72505a3700db591b3bc783",
                {
                    center: [33.3625, 126.533694],
                    crs: L.CRS.EPSG3857,
                    zoom: 11,
                    zoomControl: true,
                    preferCanvas: false,
                }
            );

            

        
    
            var tile_layer_de474aed09a0e74f6c28c8744349d9d0 = L.tileLayer(
                "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                {"attribution": "Data by \u0026copy; \u003ca target=\"_blank\" href=\"http://openstreetmap.org\"\u003eOpenStreetMap\u003c/a\u003e, under \u003ca target=\"_blank\" href=\"http://www.openstreetmap.org/copyright\"\u003eODbL\u003c/a\u003e.", "detectRetina": false, "maxNativeZoom": 18, "maxZoom": 18, "minZoom": 0, "noWrap": false, "opacity": 1, "subdomains": "abc", "tms": false}
            ).addTo(map_4793c1a92a72505a3700db591b3bc783);
        
    
            var marker_cluster_4e30e3da058a423a7cecac309426d58a = L.markerClusterGroup(
                {}
            );
            marker_cluster_4e30e3da058a423a7cecac309426d58a.options.iconCreateFunction =
                function(cluster){
                return L.divIcon({
                html:'<b>'+ cluster.getChildCount()+'</b>',
                className: 'marker-cluster marker-cluster-large',
                iconsize: new L.Point(30,30)
                });
            };
            map_4793c1a92a72505a3700db591b3bc783.addLayer(marker_cluster_4e30e3da058a423a7cecac309426d58a);
        
    
            var marker_1b9df503c369901b027f6ccad8066f75 = L.marker(
                [33.4591349705437, 126.940537521366],
                {}
            ).addTo(marker_cluster_4e30e3da058a423a7cecac309426d58a);
        
    
        var popup_5c516ae09d67f7f90c45e5863ba0e447 = L.popup({"maxWidth": "100%"});

        
            
                var html_8b6f16f21898a8e875ff85e9e776e23c = $(`<div id="html_8b6f16f21898a8e875ff85e9e776e23c" style="width: 100.0%; height: 100.0%;">성산일출봉</div>`)[0];
                popup_5c516ae09d67f7f90c45e5863ba0e447.setContent(html_8b6f16f21898a8e875ff85e9e776e23c);
            
        

        marker_1b9df503c369901b027f6ccad8066f75.bindPopup(popup_5c516ae09d67f7f90c45e5863ba0e447)
        ;

        
    
    
            var layer_control_44e218f2fd29c37e8274a16ed2e0f4ea = {
                base_layers : {
                    "openstreetmap" : tile_layer_de474aed09a0e74f6c28c8744349d9d0,
                },
                overlays :  {
                    "Jeju" : marker_cluster_4e30e3da058a423a7cecac309426d58a,
                },
            };
            L.control.layers(
                layer_control_44e218f2fd29c37e8274a16ed2e0f4ea.base_layers,
                layer_control_44e218f2fd29c37e8274a16ed2e0f4ea.overlays,
                {"autoZIndex": true, "collapsed": true, "position": "topright"}
            ).addTo(map_4793c1a92a72505a3700db591b3bc783);
        
</script>
</html>

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'bbsnote:index' %}">BBSNote</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class=""nav-link" href="{% url 'bbsnote:index' %}">bbsnote</a>
            </li>
            <li class="nav-item ">
                {% if user.is_authenticated  %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login'  %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>

templates/wordcloud.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <img src="{% static 'images/wordcloud1.png' %}">
</body>
</html>